mods.extendedcrafting.TableCrafting.addShaped("0a75dd29-d413-4f44-86cf-f3a91d770792", 0, <item:avaritia:infinity_bow>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:avaritia:infinity_ingot>, <item:minecraft:air>, <item:avaritia:neutron_nugget>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:infinity_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_nugget>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:avaritia:infinity_ingot>, <item:avaritia:endest_pearl>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_nugget>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:avaritia:infinity_catalyst>, <item:avaritia:crystal_matrix_block>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_nugget>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:avaritia:infinity_ingot>, <item:avaritia:endest_pearl>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_nugget>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:avaritia:infinity_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutron_nugget>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:avaritia:infinity_ingot>, <item:minecraft:air>, <item:avaritia:neutron_nugget>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);