mods.extendedcrafting.TableCrafting.addShaped("b27833d9-2804-491a-8d23-431bdf9b3a55", 0, <item:avaritia:infinity_legs>, [
	[<item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>], 
	[<item:avaritia:neutronium_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutronium_ingot>], 
	[<item:avaritia:neutronium_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutronium_ingot>], 
	[<item:avaritia:neutronium_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutronium_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutronium_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutronium_ingot>], 
	[<item:avaritia:neutronium_ingot>, <item:avaritia:crystal_matrix_block>, <item:avaritia:neutronium_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutronium_ingot>, <item:avaritia:crystal_matrix_block>, <item:avaritia:neutronium_ingot>], 
	[<item:avaritia:neutronium_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutronium_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutronium_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutronium_ingot>], 
	[<item:avaritia:neutronium_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutronium_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutronium_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutronium_ingot>], 
	[<item:avaritia:neutronium_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutronium_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutronium_ingot>, <item:avaritia:infinity_ingot>, <item:avaritia:neutronium_ingot>], 
	[<item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>]
]);