mods.extendedcrafting.TableCrafting.addShaped("fbd30951-8f11-43bc-81a3-4d267c2c39ca", 0, <item:avaritia:ultimate_stew>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:baked_potato>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:beetroot>, <item:minecraft:potato>, <item:minecraft:beetroot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:melon_slice>, <item:minecraft:cactus>, <item:minecraft:beetroot_soup>, <item:minecraft:cactus>, <item:minecraft:pumpkin>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:golden_apple>, <item:minecraft:apple>, <item:minecraft:glistering_melon_slice>, <item:avaritia:neutron_pile>, <item:minecraft:pumpkin_pie>, <item:minecraft:carrot>, <item:minecraft:golden_carrot>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:melon_slice>, <item:minecraft:cactus>, <item:minecraft:mushroom_stew>, <item:minecraft:cactus>, <item:minecraft:pumpkin>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:red_mushroom>, <item:minecraft:bread>, <item:minecraft:brown_mushroom>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:wheat>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);