
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Allows the mod to try to remap and convert other blocks and items from other compat mods that have been uninstalled from one world. This was made so one can uninstall such mods seamlessly having their blocks converted into Evety Compat counterparts
	remap_other_mods = false
	#Clears out and remaps all blocks registered by this mod belonging to uninstalled wood types to air or oak wood
	remap_self = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true

[leaves_type]

	[leaves_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		azalea = true
		flowering_azalea = true

	[leaves_type.blue_skies]
		bluebright = true
		starlit = true
		frostbright = true
		lunar = true
		dusk = true
		maple = true
		cherry = true
		crescent_fruit = true

	[leaves_type.biomesoplenty]
		fir = true
		redwood = true
		mahogany = true
		jacaranda = true
		palm = true
		willow = true
		dead = true
		magic = true
		umbran = true
		hellbark = true
		origin = true
		flowering_oak = true
		rainbow_birch = true
		yellow_autumn = true
		orange_autumn = true
		maple = true
		white_cherry = true
		pink_cherry = true

	[leaves_type.tconstruct]
		earth_slime = true
		sky_slime = true
		ender_slime = true

	[leaves_type.quark]
		blue_blossom = true
		lavender_blossom = true
		orange_blossom = true
		pink_blossom = true
		yellow_blossom = true
		red_blossom = true

	[leaves_type.architects_palette]
		twisted = true

	[leaves_type.twilightforest]
		twilight_oak = true
		canopy = true
		mangrove = true
		dark = true
		time = true
		transformation = true
		mining = true
		sorting = true
		thorn = true
		beanstalk = true
		rainbow_oak = true

	[leaves_type.witherstormmod]
		tainted = true

	[leaves_type.occultism]
		otherworld = true

	[leaves_type.ars_nouveau]
		blue_archwood = true
		red_archwood = true
		green_archwood = true
		purple_archwood = true

	[leaves_type.ecologics]
		coconut = true
		walnut = true

	[leaves_type.autumnity]
		maple = true
		yellow_maple = true
		orange_maple = true
		red_maple = true

	[leaves_type.croptopia]
		cinnamon = true

	[leaves_type.twigs]
		bamboo = true

	[leaves_type.atmospheric]
		rosewood = true
		morado = true
		yucca = true
		kousa = true
		aspen = true
		grimwood = true
		flowering_morado = true

[wood_type]

	[wood_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		crimson = true
		warped = true

	[wood_type.blue_skies]
		bluebright = true
		starlit = true
		frostbright = true
		lunar = true
		dusk = true
		maple = true
		cherry = true

	[wood_type.biomesoplenty]
		fir = true
		redwood = true
		cherry = true
		mahogany = true
		jacaranda = true
		palm = true
		willow = true
		dead = true
		magic = true
		umbran = true
		hellbark = true

	[wood_type.enlightened_end]
		congealed = true

	[wood_type.tconstruct]
		greenheart = true
		skyroot = true
		bloodshroom = true

	[wood_type.quark]
		azalea = true
		blossom = true

	[wood_type.architects_palette]
		twisted = true

	[wood_type.twilightforest]
		twilight_oak = true
		canopy = true
		mangrove = true
		dark = true
		time = true
		transformation = true
		mining = true
		sorting = true

	[wood_type.witherstormmod]
		tainted = true

	[wood_type.iceandfire]
		dreadwood = true

	[wood_type.ecologics]
		flowering_azalea = true
		coconut = true
		walnut = true
		azalea = true

	[wood_type.darkerdepths]
		petrified = true

	[wood_type.autumnity]
		maple = true

	[wood_type.botania]
		livingwood = true
		dreamwood = true

	[wood_type.twigs]
		bamboo = true

	[wood_type.atmospheric]
		rosewood = true
		morado = true
		yucca = true
		kousa = true
		aspen = true
		grimwood = true

